src/una_CIS_ng/Models/Penalty.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver.GeoJsonObjectModel;

namespace una_CIS_ng.Models
{
  [BsonIgnoreExtraElements]
  public class Penalty
  {
    public ObjectId id { get; set; }

    public string type { get; set; }

    public DateTime submissionTime { get; set; }

    public DateTime? deprecationTime { get; set; }

    /// <summary>
    /// Infrastructure State - For a Penalty this should always be 'Infringing'
    /// </summary>
    public string infState { get; set; }

    public string infLoc { get; set; }

    public string infDisc { get; set; }

    public string infType { get; set; }

    /// <summary>
    /// Permit State - For a Penalty this should always be 'None'
    /// </summary>
    public string permState { get; set; }

    public double[] distances { get; set; }

    public double totalDistance { get; set; }

    public GeoJsonFeatureCollection<GeoJson2DGeographicCoordinates> locations { get; set; }

    //public LonLat[][] locationRoutes { get; set; }

    public string[][] locationDescriptions { get; set; }

    public Party[] parties { get; set; }

    //[BsonElement("permit")]
    //public BsonDocument Permi { get; set; }
  }

  public static class PenaltyHelper
  {
    public static Penalty CleanParties(this Penalty pnlt)
    {
      if (ReferenceEquals(pnlt.parties, null))
      {
        pnlt.parties = new Party[0];
      }

      // clean up of unneeded elements
      var infOwner = pnlt.parties.FirstOrDefault(p => p.type == "infOwner");
      var affected = pnlt.parties.Where(p => p.type == "affected").ToList();

      if (affected != null && affected.Any())
      {
      }

      var prtys = new List<Party> { infOwner };

      foreach (var prty in prtys)
      {
        prty.CleanChildEntites();
      }
      pnlt.parties = prtys.ToArray();

      return pnlt;
    }
  }
}

src/una_CIS_ng/Models/Permit.cs
using System;
using System.Linq;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver.GeoJsonObjectModel;
using System.Collections.Generic;

namespace una_CIS_ng.Models
{
  [BsonIgnoreExtraElements]
  public class Permit
  {
    public ObjectId id { get; set; }

    public string type { get; set; }

    /// <summary>
    /// Records when a permit / permit application was first submitted
    /// </summary>
    public DateTime submissionTime { get; set; }

    /// <summary>
    /// Records when a permit was first approved (i.e. transition from permit application to permit)
    /// </summary>
    public DateTime? approvalTime { get; set; }

    /// <summary>
    /// Records when a permit / permit application was deprecated (eqv. to deleted)
    /// </summary>
    public DateTime? deprecationTime { get; set; }

    public string infState { get; set; }

    public string infLoc { get; set; }

    public string infDisc { get; set; }

    public string infType { get; set; }

    public string consType { get; set; }

    public int consPermits { get; set; }

    public string permState { get; set; }

    public double[] distances { get; set; }

    public double totalDistance { get; set; }

    public GeoJsonFeatureCollection<GeoJson2DGeographicCoordinates> locations { get; set; }

    //public LonLat[][] locationRoutes { get; set; }

    public string[][] locationDescriptions { get; set; }

    public Party[] parties { get; set; }

    //[BsonElement("permit")]
    //public BsonDocument Permi { get; set; }
  }

  public static class PermitHelper
  {
    public static Permit CleanParties(this Permit prmt)
    {
      if (ReferenceEquals(prmt.parties, null))
      {
        prmt.parties = new Party[0];
      }

      // clean up of unneeded elements
      var permitHolder = prmt.parties.FirstOrDefault(p => p.type == "holder");
      var holderContact = prmt.parties.FirstOrDefault(p => p.type == "holderContact");
      var infOwner = prmt.parties.FirstOrDefault(p => p.type == "infOwner");

      var prtys = new List<Party> { permitHolder };
      if (holderContact != null)
      {
        prtys.Add(holderContact);
      }
      if (infOwner != null)
      {
        prtys.Add(infOwner);
      }
      foreach (var prty in prtys)
      {
        prty.CleanChildEntites();
      }
      prmt.parties = prtys.ToArray();

      return prmt;
    }
  }
}

src/una_CIS_ng/Controllers/HomeController.cs
using System;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using una_CIS_ng.Core;
using una_CIS_ng.Models;

namespace una_CIS_ng.Controllers
{
  public class HomeController : Controller
  {
    private readonly AppCodes _appCodes;

    public HomeController(IOptions<AppCodes> optionsAccessor)
    {
      _appCodes = optionsAccessor.Value;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult About()
    {
      ViewData["Message"] = Constants.LasimraAbbr + ", " + Constants.UnaAbbr + ", " + Constants.CisAbbr;

      return View();
    }

    public IActionResult Permit()
    {
      ViewData["Message"] = "Right-of-Way / Construction";
      ViewData["GoogleAPIKey"] = _appCodes.GoogleApiKey;
      ViewData["GoogleAPIBrowserKey"] = _appCodes.GoogleApiBrowserKey;

      return View();
    }

    public IActionResult Penalty()
    {
      ViewData["Message"] = "Penalty";
      ViewData["GoogleAPIKey"] = _appCodes.GoogleApiKey;
      ViewData["GoogleAPIBrowserKey"] = _appCodes.GoogleApiBrowserKey;

      return View();
    }

    public IActionResult PermitInfo()
    {
      ViewData["Message"] = "General Permit Information";

      return View();
    }

    public IActionResult PermitFee()
    {
      ViewData["Message"] = "Permit Fee Estimator";

      return View();
    }

    public IActionResult Map()
    {
      ViewData["Message"] = "Infrastructure Map";
      ViewData["GoogleAPIKey"] = _appCodes.GoogleApiKey;
      ViewData["GoogleAPIBrowserKey"] = _appCodes.GoogleApiBrowserKey;

      return View();
    }

    public IActionResult Contact()
    {
      ViewData["Message"] = "Contacts for the " + Constants.UnaFullTitle;

      return View();
    }

    public IActionResult Error()
    {
      return View();
    }

    [HttpPost("~/cspreport")]
    public IActionResult CspReport([FromBody] CspReportRequest request)
    {
      var reqCspRep = request.CspReport;
      // TODO: log request to a datastore somewhere
      var cspViolation = new StringBuilder("CSP Violation:");
      cspViolation.AppendFormat("  URIs- Document:{0}, Blocked:{1}", reqCspRep.DocumentUri, reqCspRep.BlockedUri);
      cspViolation.AppendLine();
      //if (!string.IsNullOrWhiteSpace(reqCspRep.OriginalPolicy))
      //{
      //  cspViolation.AppendFormat("  Original Policy:{0}", reqCspRep.OriginalPolicy);
      //  cspViolation.AppendLine();
      //}
      cspViolation.AppendFormat("  Directives- Violated:{0}, Effective:{1} ", reqCspRep.ViolatedDirective, reqCspRep.EffectiveDirective);
      cspViolation.AppendLine();
      if (!string.IsNullOrWhiteSpace(reqCspRep.Referrer))
      {
        cspViolation.AppendFormat("  Referrer:{0}", reqCspRep.Referrer);
        cspViolation.AppendLine();
      }
      cspViolation.AppendFormat(" Status Code:{0}", reqCspRep.StatusCode);

      Console.WriteLine(cspViolation.ToString());

      return Ok();
    }
  }
}

src/una_CIS_ng/Controllers/PdfFormController.cs
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using iTextSharp.text;
using iTextSharp.text.html;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using una_CIS_ng.Core;

namespace una_CIS_ng.Controllers
{
  public class PdfFormController : Controller
  {
    protected ICompositeViewEngine ViewEngine;

    public PdfFormController(ICompositeViewEngine viewEngine)
    {
      ViewEngine = viewEngine;
    }

    public IActionResult PermitApplicationRoW()
    {
      var htmlContent = RenderViewToString();

      return File(GenerateHtmlToPDFDocument(htmlContent), "application/pdf");
    }

    /// <summary>
    /// Generate PDF from HTML
    /// </summary>
    /// <param name="html"></param>
    /// <returns></returns>
    public byte[] GenerateHtmlToPDFDocument(string html)
    {
      var workStream = new MemoryStream();
      var pdfDoc = new Document(PageSize.A4);
      PdfWriter.GetInstance(pdfDoc, workStream).CloseStream = false;
      var parser = new HTMLWorker(pdfDoc);

      // Get chapter content
      var chapter = CreateChapterContent(html);

      pdfDoc.Open();

      // Add chapter content to PDF
      pdfDoc.Add(chapter);

      pdfDoc.Close();

      var byteInfo = workStream.ToArray();
      workStream.Write(byteInfo, 0, byteInfo.Length);
      workStream.Position = 0;

      // Generate TOC for existing content
      return GeneratePDFTOCContent(byteInfo, html);
    }

    /// <summary>
    /// Generate PDF To Content
    /// </summary>
    /// <param name="content"></param>
    /// <param name="html"></param>
    /// <returns></returns>
    public byte[] GeneratePDFTOCContent(byte[] content, string html)
    {
      var reader = new PdfReader(content);
      var sb = new StringBuilder();

      // Title of PDF
      sb.Append("<h2><strong style='text-align:center'>Demo for Load More Button in Kendo UI Grid</strong></h2><br>");

      // Begin to create TOC
      sb.Append("<table>");
      sb.Append(string.Format("<tr><td width='80%'><strong>{0}</strong></td><td align='right' width='10%'><strong>{1}</strong></td></tr>", "Section", "Page"));
      using (var ms = new MemoryStream())
      {
        // XML document generated by iText 
        SimpleBookmark.ExportToXML(SimpleBookmark.GetBookmark(reader), ms, "UTF-8", false);

        // rewind to create xmlreader
        ms.Position = 0;
        using (var xr = XmlReader.Create(ms))
        {
          xr.MoveToContent();

          const string format = @"<tr><td width='80%'>{0}</td><td align='right' width='10%'>{1}</td></tr>";

          // extract page number from 'Page' attribute 
          var re = new Regex(@"^\d+");
          while (xr.Read())
          {
            if (xr.NodeType != XmlNodeType.Element || xr.Name != "Title" || !xr.IsStartElement())
            {
              continue;
            }

            var page = re.Match(xr.GetAttribute("Page")).Captures[0].Value;
            xr.Read();

            if (xr.NodeType != XmlNodeType.Text)
            {
              continue;
            }

            var text = xr.Value.Trim();
            var pageSection = int.Parse(page) + 1;
            sb.Append(string.Format(format, text, pageSection));
          }
        }
      }
      sb.Append("</table>");

      var workStream = new MemoryStream();
      var document = new Document(reader.GetPageSizeWithRotation(1));
      var writer = PdfWriter.GetInstance(document, workStream);
      writer.CloseStream = false;

      document.Open();
      document.NewPage();

      // Add TOC
      var styles = new StyleSheet();
      styles.LoadTagStyle("h2", HtmlTags.HORIZONTALALIGN, "center");
      styles.LoadTagStyle("h2", HtmlTags.COLOR, "#F90");

      foreach (IElement element in HTMLWorker.ParseToList(new StringReader(sb.ToString()), styles))
      {
        document.Add(element);
      }

      // Append your chapter content again
      var chapter = CreateChapterContent(html);
      document.Add(chapter);

      document.Close();
      writer.Close();

      var byteInfo = workStream.ToArray();
      workStream.Write(byteInfo, 0, byteInfo.Length);
      workStream.Position = 0;

      return byteInfo;
    }

    /// <summary>
    /// Create chapter content from html
    /// </summary>
    /// <param name="html"></param>
    /// <returns></returns>
    public Chapter CreateChapterContent(string html)
    {
      // Declare a font to used for the bookmarks
      var bookmarkFont = FontFactory.GetFont(FontFactory.HELVETICA, 16, Font.NORMAL, new Color(255, 153, 0));

      var chapter = new Chapter(new Paragraph(""), 0) { NumberDepth = 0 };

      // Create css for some tag
      var styles = new StyleSheet();

      styles.LoadTagStyle("h2", HtmlTags.HORIZONTALALIGN, "center");
      styles.LoadTagStyle("h2", HtmlTags.COLOR, "#F90");
      styles.LoadTagStyle("pre", "size", "10pt");

      // Split H2 Html Tag
      var pattern = @"<\s*h2[^>]*>(.*?)<\s*/h2\s*>";
      var result = Regex.Split(html, pattern);

      // Create section title & content
      var sectionIndex = 0;
      foreach (var item in result)
      {
        if (string.IsNullOrEmpty(item)) continue;

        if (sectionIndex % 2 == 0)
        {
          chapter.AddSection(20f, new Paragraph(item, bookmarkFont), 0);
        }
        else
        {
          foreach (IElement element in HTMLWorker.ParseToList(new StringReader(item), styles))
          {
            chapter.Add(element);
          }
        }

        sectionIndex++;
      }

      chapter.BookmarkTitle = Constants.UnaAbbr + " " + Constants.CisAbbr;
      return chapter;
    }


    /// <summary>
    /// Render View to String
    /// </summary>
    /// <param name="viewName"></param>
    /// <returns></returns>
    protected string RenderViewToString(string viewName = null)
    {
      viewName = viewName ?? ControllerContext.ActionDescriptor.Name;
      ViewData.Model = null;
      //if (string.IsNullOrEmpty(viewName))
      //  viewName = ActionContext.ActionDescriptor.Name;

      using (var sw = new StringWriter())
      {
        var view = ViewEngine.FindView(ControllerContext, viewName, true).View;
        var viewContext = new ViewContext(ControllerContext, view, ViewData, TempData, sw, new HtmlHelperOptions());

        view.RenderAsync(viewContext).Wait();

        return sw.GetStringBuilder().ToString();
      }
    }
  }
}

src/una_CIS_ng/Views/Home/Contact.cshtml
@using una_CIS_ng.Core

@{
  ViewData["Title"] = "Contact";
}

<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
  Top Floor, Block A, Elaganza Complex,<br />
  Plot 33, Mobolaji Johnson Avenue,<br />
  Oregun, Ikeja, @Constants.LagosAbbr, Nigeria
</address>

<address>
  <abbr title="Phone">P:</abbr>
  +234.(0)908 708 1484
</address>

<address>
  <abbr title="Phone">P:</abbr>
  +234.(0)908 708 1488
</address>

<iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d4954.180418325345!2d3.3700508153287942!3d6.604047895224219!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x103b92517ca8bfa5%3A0x9dc9ade03a7ede59!2s33+Mobolaji+Johnson+Way!3m2!1d6.604047899999999!2d3.3722395!5e1!3m2!1sen!2sng!4v1462360633142" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

src/una_CIS_ng/Views/Home/PermitInfo.cshtml
@using una_CIS_ng.Core

@{
  ViewData["Title"] = "Permit Information";
}

<h2>@ViewData["Title"]</h2>

<div class="container">
  <div class="row">
    <div class="col-md-9 col-lg-10" role="main">
      <h3 id="PermitInfoIssuingPermits">General Requirements for Issuing Permits</h3>
      <p>To obtain a Permit for your infrastructure several things are required:</p>
      <ul>
        <li>The Infrastructure Owner / Permit Holder must be the one to make the permit application.</li>
        <li>
          The Permit Holder and Infrastructure Owner must be identified.<br />
          <small>These can be the same person / organisation.<br /> If they are not the same then the Permit Holder must be an authorised agent of the Infrastructure Owner.</small>
        </li>
        <li>Other people and organisations may need to be identified.</li>
        <li>Details about your infrastructure must be clearly identified.</li>
        <li>Relevant documents, e.g. engineers reports, must be provided.</li>
        <li>The relevant fees, charges and penalties must be paid.</li>
        <li><small>(Some other agencies may require you to obtain relevant permits / authorisation also - @Constants.LasimraAbbr and its authorised agencies are not responsible for this)</small></li>
      </ul>
      <h3 id="PermitInfoKeepingPermits">General Requirements for Keeping Permits</h3>
      <p>To keep a Permit for your infrastructure:</p>
      <ul>
        <li>You must notify of any changes to the details for the Permit Holder or Infrastructure Owner.</li>
        <li>Notify of any significant discrepancies about your infrastructure from that detailed on your Permit.</li>
        <li>Make use of the Permit within a suitable time frame.</li>
        <li>Any follow-on activities required by the Permit type must be performed or paid for, e.g. remediation works after construction.</li>
      </ul>
      <h3 id="PermitInfoPermitParties">Parties to the Permit</h3>
      <p>For any Permit there are several different roles for which different persons or organisations need to be identified. These are the "Parties to the Permit".</p>
      <dl class="dl-horizontal">
        <dt id="PermitInfoPermitHolder">Permit Holder</dt>
        <dd>
          The Person or Organisation who 'owns' the permit itself.
          They do not have to own the infrastructure that is covered by the permit,
          but if they do not own the infrastructure then they must be authorised by the Infrastructure Owner to act as the representative.
          For instance an organisation may set up a management company to 'hold' all of its permits.
          The Permit Holder must be identified for each Permit.
        </dd>
        <dt id="PermitInfoHolderContact">Permit Holder Contact</dt>
        <dd>
          A Person
          - When the Permit Holder is an Organisation, or they are not based in Nigeria, then a local contact person is required.
          The Permit Holder Contact is this person.
        </dd>
        <dt id="PermitInfoInfrastructureOwner">Infrastructure Owner</dt>
        <dd>
          Is the owner of the infrastructure covered by the Permit.
        </dd>
        <dt id="PermitInfoPrimaryContractor">Primary Contractor</dt>
        <dd>
          For a Construction Permit (which includes decommissioning) the Primary Contractor is the Person or Organisation responsible for the actual construction activities.
        </dd>
        <dt id="PermitInfoContractorContact">Primary Contractor Contact</dt>
        <dd>
          A Person
          - When the Primary Contractor is an Organisation, or they are not based in Nigeria, then a local contact person is required.
          The Primary Contractor Contact is this person.
        </dd>
      </dl>
      <p>For a Right-of-Way Permit most operators will be the Permit Holder and Infrastructure Owner, and they will have a person from within their organisation to be the Permit Holder Contact.</p>
      <h3 id="PermitInfoFees">Fees, Charges and Penalties</h3>
      <p>
        Note: These fees, charges and penalties, and the rules related to their application,
        are subject to change at the discretion of @Constants.LasimraAbbr and at the discretion of its appointed agencies (after consultation with @Constants.LasimraAbbr).
        No refund is offered for any changes.
      </p>
      <div class="table-responsive" ng-controller="feeCalculatorController">
        <table class="table table-striped table-condensed table-hover">
          <thead>
            <tr>
              <th class="col-xs-2">Type</th>
              <th class="col-xs-7">Description</th>
              <th class="col-xs-1 text-right">Rate</th>
              <th class="col-xs-2">&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            <tr class="animate-show" ng-repeat="fee in calc.fees">
              <td>{{fee.feeType}}</td>
              <td>{{fee.name}}</td>
              <td class="text-right">{{fee.rate | currency: "N&nbsp;": 0}}</td>
              <td>{{fee.rateDesc()}}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h3 id="PermitInfoNotes">Important Notes about Permits</h3>
      <p id="PermitInfoPayment">Paying for Permits</p>
      <ul>
        <li>Permits are only issued after the full amount in fees, charges and penalties have been paid (and after all other conditions have been met)</li>
        <li>Payment is currently only accepted in the form of a bank draft / bank cheque</li>
        <li>Any charges imposed by the bank issuing the bank draft / bank cheque are in addition to any fees, charges and penalties imposed by @Constants.LasimraAbbr</li>
        <li>You may pay for multiple permits with a single payment</li>
        <li>Refunds are not offered for overpayments or payments (in full or part) for a permit that is no longer required</li>
        <li>No facility for maintaining credit with @Constants.LasimraAbbr for 'unused' payments presently exists</li>
      </ul>
      <p id="PermitInfoReissues">Permits may be reissued at the discretion of @Constants.LasimraAbbr or its authorised agencies, for several reasons:</p>
      <ul>
        <li>The Permit Holder has changed their name.</li>
        <li>The Permit itself has been transferred (e.g. sold) to another party.</li>
        <li>There were significant discrepancies between the actual infrastructure and that described on the Permit.</li>
        <li>There has been a change of law, requiring @Constants.LasimraAbbr or its authorised agencies to reissue the Permit.</li>
        <li>Conditions imposed upon the Permit have been changed.</li>
        <li>In general, any significant change to the details of a Permit, or to the conditions of a Permit, will result in that Permit being invalidated, and a new Permit being issued.</li>
        <li>Where a Permit must be reissued because of something the Permit Holder / Infrastructure Owner has done (or not done as the Permit required) then it is likely that the Permit Holder / Infrastructure Owner will be charged a fee for the Permit to be reissued.</li>
      </ul>
      <p id="PermitInfoAuthority">Authority to Hold Permits</p>
      <ul>
        <li>If a permit is held by a person / organisation that is not an authorised agent of the Infrastructure Owner then that permit is invalid.</li>
        <li>Any party that obtains a permit over some infrastructure, when they do not have authority to do so, is subject to penalties.</li>
      </ul>
      <p id="PermitInfoInvalidation">Invalidated Permits</p>
      <ul>
        <li>There is no refund offered for any permit that has been invalidated.</li>
        <li>Invalidated permits are still part of the official record.</li>
        <li>Invalidated permits may not be restored to a valid state.  However a new permit be issued under appropriate circumstances.</li>
      </ul>
      <p id="PermitInfoTimeframes">Permits have either of two basic time frames that may apply to them:</p>
      <ul>
        <li>Short Term - Such as Construction Permits</li>
        <li>Long Term / Indefinite - Such as Right-of-Way Permits for underground infrastructure</li>
      </ul>
      <p id="PermitInfoShortTerm">Short Term Permits</p>
      <ul>
        <li>Construction permits have a short life span and are limited to the area applied for.</li>
        <li>Conditions will be imposed upon Construction Permits on the basis of how the construction will impact the neighbouring community, the use of public assets such as roads and footpaths, and the potential impact for emergency services to perform their duties.</li>
        <li>It is strongly recommended that when the construction will cover a significant area, e.g. installing underground fiber, that multiple Construction Permits be applied for covering each section of the area being worked on, and spread out over time also. Taking into account all of the factors that will affect your construction.</li>
      </ul>
      <p id="PermitInfoLongTerm">Long Term Permits</p>
      <ul>
        <li>Long Term / Indefinite Permits apply for the life span of the infrastructure.</li>
        <li>It is the obligation of the Infrastructure Owner to ensure that the infrastructure is well maintained. This includes all of the peripheral infrastructure and any features to ensure public safety.</li>
        <li>It is the responsibility of the Infrastructure Owner to ensure that the infrastructure is decommissioned when no longer required.</li>
        <li>Infrastructure Owners who fail to maintain their infrastructure and/or decommission it when no longer required are subject to penalties.</li>
      </ul>
    </div>
    <nav class="col-md-3 col-lg-2 hidden-xs hidden-sm hidden-print" id="rightSideNav">
      <ul class="nav nav-stacked affix-top" id="sidebar">
        <li>
          <a href="#PermitInfoIssuingPermits">Issuing Permits</a>
        </li>
        <li>
          <a href="#PermitInfoKeepingPermits">Keeping Permits</a>
        </li>
        <li>
          <a href="#PermitInfoPermitParties">Permit Parties</a>
          <ul class="nav nav-stacked">
            <li><a href="#PermitInfoPermitHolder">Permit Holder</a></li>
            <li><a href="#PermitInfoHolderContact">Holder Contact</a></li>
            <li><a href="#PermitInfoInfrastructureOwner">Infrastructure Owner</a></li>
            <li><a href="#PermitInfoPrimaryContractor">Primary Contractor</a></li>
            <li><a href="#PermitInfoContractorContact">Contractor Contact</a></li>
          </ul>
        </li>
        <li>
          <a href="#PermitInfoFees">Fees, Charges, Penalties</a>
        </li>
        <li>
          <a href="#PermitInfoNotes">Notes</a>
          <ul class="nav nav-stacked">
            <li><a href="#PermitInfoPayment">Payment</a></li>
            <li><a href="#PermitInfoReissues">Permit Reissue</a></li>
            <li><a href="#PermitInfoAuthority">Holding Authority</a></li>
            <li><a href="#PermitInfoInvalidation">Invalidation</a></li>
            <li><a href="#PermitInfoTimeframes">Permit Timeframes</a></li>
            <li><a href="#PermitInfoShortTerm">Short Term</a></li>
            <li><a href="#PermitInfoLongTerm">Long Term</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>

@*<a asp-controller="PdfForm" asp-action="PermitApplicationRoW">Static PDF Permit Application - Right of Way</a>*@

@section scripts
{
  <environment names="Development">
    <script src="~/js/services/feeDefinitionServiceFactory.js" asp-append-version="true"></script>
    <script src="~/js/factories/feeDefinitionFactory.js" asp-append-version="true"></script>
    <script src="~/js/controllers/feeCalculatorController.js" asp-append-version="true"></script>
  </environment>
  <environment names="Staging,Production">
    <script src="~/js/services/feeDefinitionServiceFactory.js" asp-append-version="true"></script>
    <script src="~/js/factories/feeDefinitionFactory.js" asp-append-version="true"></script>
    <script src="~/js/controllers/feeCalculatorController.js" asp-append-version="true"></script>
  </environment>
}